# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [45]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

In [0]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import confusion_matrix


## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
iris_data = load_iris()
#iris_data

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
data = iris_data.data
target = iris_data.target
#print(target.reshape(-1, 1))

In [0]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data= np.c_[data, target],
                     columns= iris_data['feature_names'] + ['target'])

data = df.drop('target', axis = 1)
target = df['target']

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
X_train, X_test, y_train, y_test = train_test_split(data,target, test_size = 0.25, random_state = 0)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
#encoder = OneHotEncoder(categorical_features = [0])
#y = encoder.fit_transform(target)
#y.shape

#X_train, X_test, y_train, y_test = train_test_split(data,y, test_size = 0.25, random_state = 0)
#y_train = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
#y_test = encoder.fit_transform(y_test.reshape(-1, 1)).toarray()

y_train = tf.keras.utils.to_categorical(y_train, num_classes = 3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes = 3)

In [199]:
y_train.shape
X_train.shape

(112, 4)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(Dense(4, input_shape=(4,)))
model.add(Dense(3, activation='softmax', name='output'))


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [203]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 4)                 20        
_________________________________________________________________
output (Dense)               (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [204]:
model.fit(X_train, y_train,           
          validation_data=(X_test,y_test),
          epochs=100,
          batch_size=32)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 1ms/sample - loss: 2.8244 - accuracy: 0.3125 - val_loss: 2.5260 - val_accuracy: 0.2368
Epoch 2/100
112/112 [==============================] - 0s 131us/sample - loss: 2.2347 - accuracy: 0.3571 - val_loss: 2.1175 - val_accuracy: 0.1579
Epoch 3/100
112/112 [==============================] - 0s 166us/sample - loss: 2.0155 - accuracy: 0.0982 - val_loss: 1.9715 - val_accuracy: 0.0263
Epoch 4/100
112/112 [==============================] - 0s 164us/sample - loss: 1.8732 - accuracy: 0.0536 - val_loss: 1.8577 - val_accuracy: 0.1053
Epoch 5/100
112/112 [==============================] - 0s 165us/sample - loss: 1.7586 - accuracy: 0.2857 - val_loss: 1.7010 - val_accuracy: 0.0789
Epoch 6/100
112/112 [==============================] - 0s 207us/sample - loss: 1.6420 - accuracy: 0.1518 - val_loss: 1.5778 - val_accuracy: 0.3947
Epoch 7/100
112/112 [==============================] - 0s 156us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [210]:
y_pred = model.predict_classes(X_test)
print(y_pred)


[2 2 0 2 0 2 0 2 2 2 2 2 2 2 2 0 2 2 0 0 2 2 0 0 2 0 0 2 2 0 2 1 0 2 2 2 0
 2]


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [209]:
print(y_test[0:5])

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]




---



In [80]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [82]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [85]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()
root_path = '/content/drive/My Drive/Colab Notebooks/'
ds = pd.read_csv(root_path+'R6/IN/prices.csv')
ds.head(10)

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0
5  2016-01-12 00:00:00   WLTW  115.510002  ...  114.500000  116.059998  1098000.0
6  2016-01-13 00:00:00   WLTW  116.459999  ...  112.589996  117.070000   949600.0
7  2016-01-14 00:00:00   WLTW  113.510002  ...  110.050003  115.029999   785300.0
8  2016-01-15 00:00:00   WLTW  113.330002  ...  111.919998  114.879997  1093700.0
9  2016-01-19 00:00:00   WLTW  113.660004  ...  109.870003  115.870003  1523500.0

[10 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
ds = ds.drop(['date', 'symbol'], axis=1)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [89]:
price_data = ds.iloc[0:1000,:]
price_data

open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
..          ...         ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [99]:
X = price_data.iloc[:,0:4].values 
y = price_data.iloc[:,4].values/1000000
print(y)

[2.163600e+00 2.386400e+00 2.489500e+00 2.006300e+00 1.408600e+00
 1.098000e+00 9.496000e-01 7.853000e-01 1.093700e+00 1.523500e+00
 1.653900e+00 9.443000e-01 7.449000e-01 7.038000e-01 5.631000e-01
 8.961000e-01 6.804000e-01 7.499000e-01 5.742000e-01 6.948000e-01
 8.963000e-01 9.563000e-01 9.971000e-01 1.200500e+00 1.725200e+00
 1.946000e+00 1.319500e+00 9.224000e-01 1.185100e+00 9.215000e-01
 4.409000e-01 1.244300e+00 6.813000e-01 4.112000e-01 4.473000e-01
 5.592000e-01 4.599000e-01 9.716000e-01 6.941000e-01 1.159600e+00
 8.847000e-01 6.920000e-01 8.980000e-01 8.445000e-01 7.965000e-01
 4.168000e-01 5.902000e-01 4.951000e-01 5.158000e-01 5.621000e-01
 8.093000e-01 1.607300e+00 1.001300e+00 7.114000e-01 4.442000e-01
 5.341000e-01 7.982000e-01 5.910000e-01 4.432000e-01 5.780000e-01
 7.651000e-01 5.143000e-01 1.150000e+00 2.035300e+00 7.022000e-01
 6.891000e-01 5.532000e-01 7.759000e-01 6.217000e-01 3.581000e-01
 9.393000e-01 7.355000e-01 9.246000e-01 6.588000e-01 1.055400e+00
 6.953000e

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
import numpy as np

In [0]:
X = np.asarray(X,dtype=np.float32)
y = np.asarray(y,dtype=np.float32)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [105]:
X = tf.math.l2_normalize(X)
X.shape

TensorShape([1000, 4])

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [111]:
#Train for 100 Steps
for i in range(100):
    
    w, b = train(X, y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(y, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16759
Current Loss on iteration 1 235.09299
Current Loss on iteration 2 234.06102
Current Loss on iteration 3 233.06998
Current Loss on iteration 4 232.11781
Current Loss on iteration 5 231.20381
Current Loss on iteration 6 230.32585
Current Loss on iteration 7 229.48265
Current Loss on iteration 8 228.67297
Current Loss on iteration 9 227.89539
Current Loss on iteration 10 227.14832
Current Loss on iteration 11 226.43114
Current Loss on iteration 12 225.74234
Current Loss on iteration 13 225.0808
Current Loss on iteration 14 224.44553
Current Loss on iteration 15 223.835
Current Loss on iteration 16 223.24931
Current Loss on iteration 17 222.68655
Current Loss on iteration 18 222.14595
Current Loss on iteration 19 221.62688
Current Loss on iteration 20 221.12842
Current Loss on iteration 21 220.6498
Current Loss on iteration 22 220.18993
Current Loss on iteration 23 219.74841
Current Loss on iteration 24 219.32425
Current Loss on iteration 25 218.91705


### Observe values of Weight
- Print the updated values

In [112]:
#Check Weights and Bias
print('Weights:\n', w.numpy())


Weights:
 [[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [113]:
print('Bias:\n',b.numpy())

Bias:
 [4.607657]
